### ISSUE TITLE
Undefined Value on Upload

### ISSUE THREAD

**Issue by jacobedawson** [jacobedawson/node-accounts-project#14]
TypeError: Cannot read property '_id' of undefined
    at Object.handle (/mnt/data/1/server.js:2762:33)
    at next_layer (/mnt/data/1/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/mnt/data/1/node_modules/express/lib/router/route.js:107:5)
    at c (/mnt/data/1/node_modules/express/lib/router/index.js:195:24)
    at Function.proto.process_params (/mnt/data/1/node_modules/express/lib/router/index.js:251:12)
    at next (/mnt/data/1/node_modules/express/lib/router/index.js:189:19)
    at next (/mnt/data/1/node_modules/express/lib/router/index.js:166:38)
    at next (/mnt/data/1/node_modules/express/lib/router/index.js:166:38)
    at next (/mnt/data/1/node_modules/express/lib/router/index.js:166:38)
    at next (/mnt/data/1/node_modules/express/lib/router/index.js:166:38)

**Comment by jacobedawson** [comment]
Added in a default, and a return statement if the user is undefined: 

req.user = req.user || undefined;
            if (req.user === undefined) {
                res.send(403, 'user undefined');
                return;
            }
