### ISSUE TITLE
Undefined Error on Group Invite

### ISSUE THREAD

**Issue by jacobedawson** [jacobedawson/node-accounts-project#35]
[90mGET /images/icons/group_chat_icon.png [32m200 [90m8ms - 590b[0m

/mnt/data/2/server.js:3580
                            if(isEquivalent(group.groupInvites[i].id, userID))
                                                                 ^
TypeError: Cannot read property 'id' of undefined
    at Promise.<anonymous> (/mnt/data/2/server.js:3580:66)
    at Promise.<anonymous> (/mnt/data/2/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/mnt/data/2/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/mnt/data/2/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at /mnt/data/2/node_modules/mongoose/lib/query.js:1406:13
    at model.Document.init (/mnt/data/2/node_modules/mongoose/lib/document.js:254:11)
    at completeOne (/mnt/data/2/node_modules/mongoose/lib/query.js:1404:10)
    at Object.cb (/mnt/data/2/node_modules/mongoose/lib/query.js:1158:11)
    at Object._onImmediate (/mnt/data/2/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
[2015-06-02T12:23:48.995Z] Application CRASH detected. Exit code 8.

**Comment by jacobedawson** [comment]
It looks like on line 3580, to do with removing group requests, I did a check for 'group' and 'groupInvites' but didn't check for the length of groupInvites (which had no length, meaning that groupInvites[i] was undefined, which caused the error). 

I've since changed the code to check for the group, and once confirmed check that the array exists and also that it has a length > 0. 

This bug should be fixed now, although I'm not sure why the groupInvites array was empty...
