### ISSUE TITLE
Crash during invite

### ISSUE THREAD

**Issue by jacobedawson** [jacobedawson/node-accounts-project#45]
2015-06-26T12:25:16+0000 <log> server.js:3917 (Promise.<anonymous>) Found the invite, removing from the group

/mnt/data/2/server.js:3921
                            if(isEquivalent(group.groupInvites[i].id, userID))
                                                                 ^
TypeError: Cannot read property 'id' of undefined
    at Promise.<anonymous> (/mnt/data/2/server.js:3921:66)
    at Promise.<anonymous> (/mnt/data/2/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
    at Promise.emit (events.js:95:17)
    at Promise.emit (/mnt/data/2/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
    at Promise.fulfill (/mnt/data/2/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
    at /mnt/data/2/node_modules/mongoose/lib/query.js:1406:13
    at model.Document.init (/mnt/data/2/node_modules/mongoose/lib/document.js:254:11)
    at completeOne (/mnt/data/2/node_modules/mongoose/lib/query.js:1404:10)
    at Object.cb (/mnt/data/2/node_modules/mongoose/lib/query.js:1158:11)
    at Object._onImmediate (/mnt/data/2/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
[2015-06-26T12:25:16.803Z] Application CRASH detected. Exit code 8.

**Comment by jacobedawson** [comment]
added an undefined check into this code
